### ISSUE TITLE
stats.js r17 is broken

### ISSUE THREAD

**Issue by gera2ld** [cdnjs/cdnjs#11222] opened 2017-05-11 01:29 UTC
ref: a67a9d40
The uncompressed file is using ES6 modules and cannot be executed directly.
The compressed file is completely broken.

**Comment by pvnr0082t** [comment] 2017-05-11 13:54
@PeterDaveHello There is official minified file(https://github.com/mrdoob/stats.js/blob/r17/build/stats.min.js). Should we remove the files in version [17](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/stats.js/17)/[r17](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/stats.js/r17) in cdnjs and put the official minified file into the directories?

**Comment by PeterDaveHello** [comment] 2017-05-14 15:38
@pvnr0082t broken/difference confirmed?

**Comment by extend1994** [comment] 2017-12-15 14:16
@PeterDaveHello `Stats.js` in r17/17 are the same as the upstream. But ` Stats.min.js` is different. I guess it's minified by the bot.
In addition, I notice that even though `version` in lib's [package.json](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/stats.js/package.json) is still "r16". And auto-update config seem to needs a update. There is also npm package https://www.npmjs.com/package/stats.js.

**Comment by xtuc** [comment] 2020-05-05 20:59
I suspect that new versions of that package were pushed since 2017... Closing, feel free to continue to comment

**Closed by xtuc** 2020-05-05 20:59 UTC
Labels: :rotating_light: High Priority
