### ISSUE TITLE
admin-lte is not found

### ISSUE THREAD

**Issue by efpies** [cdnjs/cdnjs#13896] opened 2020-04-23 17:58 UTC
libman can't resolve admin-lte dependency.

`libman.json: [LIB002] The "admin-lte@2.4.18" library could not be resolved by the "cdnjs" provider`

Not available here: https://cdnjs.com/libraries/admin-lte

![image](https://user-images.githubusercontent.com/1215572/80132478-6989f100-85a4-11ea-9f63-b48483e76aab.png)

But it's available here: https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.18/css/AdminLTE.min.css

It worked like 12 h ago.

**Comment by MattIPv4** [comment] 2020-04-23 20:11
Hey there @efpies,

I'm not able to reproduce this, https://cdnjs.com/libraries/admin-lte loads just fine for me, including the mentioned version directly: https://cdnjs.com/libraries/admin-lte/2.4.18

Any other info you can provide on the error you're facing?

**Comment by efpies** [comment] 2020-04-23 22:12
When I was posting this issue, https://cdnjs.com/libraries/admin-lte was blank. But it wasn't the case for other libraries. So I'm not sure that it was an issue on my side. Unless adblock decided to block specifically the `admin-lte` lib and then decided to stop doing it. Or cloudflare.
When you replied, I checked the site, and it indeed showed me a non-blank page. But libman still wasn't able to download dependencies. I tried to do `libman restore`, but it failed to download the `admin-lte` package.
After some time, it finally worked 🤷‍♂️

But now I'm facing a different issue, with the `ionicons` library (https://cdnjs.com/libraries/ionicons/4.5.6). The web page loads well and I'm able to download the source files from the browser, but `libman restore` only fetches the metadata file for this dependency and calls it a day. And there are no errors in the log. However, if I switch to `jsdelivr` specifically for ionicons, libman correctly downloads all files listed in the metadata file.

I don't know how to check what is going wrong as libman doesn't provide any useful logs.

I cleaned the cache like 10 times at this point. But I guess it has something to do with cdnjs itself as I have a dozen dependencies linked to it and only have problems with couple of them. Namely `admin-lte` and `jquery` that libman couldn't fetch from cdnjs (works now), or `ionicons` where only the metadata file is being downloaded.

**Comment by MattIPv4** [comment] 2020-04-23 22:17
This sounds really odd that you're seeing failures on cdnjs.com as well as the API/CDN, and we're seeing no other reports of this at all.

It might be worth just waiting a while and seeing if its a local issue for you with some weird cache issues. If it persists after then we can take a closer look, though it may be better to reach out to the Libman folks as they'll have more idea what exactly it depends on from us.

**Comment by MattIPv4** [comment] 2020-04-24 09:59
Hi there,

After doing some more digging on this today, we believe this was a slight hiccup with one of our API origins that was missing some recent library data.

We’ve just updated this and it should now be available again.

Hope that helps!

**Comment by xtuc** [comment] 2020-04-28 20:01
Is this resolved?

**Comment by MattIPv4** [comment] 2020-05-03 20:13
No further progress, closing.

**Closed by MattIPv4** 2020-05-03 20:13 UTC
Labels: :radioactive: Bug
