### ISSUE TITLE
[Request] Add jQuery-Storage-API

### ISSUE THREAD

**Issue by vipaware** [cdnjs/cdnjs#6420] opened 2015-12-07 15:18 UTC
**Library name:** jQuery-Storage-API
**Git repository url:** https://github.com/julien-maurel/jQuery-Storage-API
**npm package url(optional):** 
**License(s):** MIT license
**Official homepage:** https://github.com/julien-maurel/jQuery-Storage-API
**Wanna say something? Leave message here:**
I would like you to host this neat jQuery plugin. It's strange nobody requested it yet.
Generally, only this file should be hosted:
- _jquery.storageapi.min.js_

but you also might want to host non-minified version:
- _jquery.storageapi.js_

Thanks a lot!
PS. It would be super awesome if you could let me know when it's hosted, I would update my files immediately then. But it's OK if you ignore me... everyone is ignoring me these days.

**Comment by maruilian11** [comment] 2015-12-18 08:46
@vipaware i will send PR immediately, and you will be informed when the issue is closed which means the lib is hosted :+1:

**Closed** 2015-12-18 11:47 UTC
Labels: in progress
