### ISSUE TITLE
[Request] Update fancybox library to latest version 3

### ISSUE THREAD

**Issue by glowworms** [cdnjs/cdnjs#10802] opened 2017-03-06 05:59 UTC
**Library name:** fancybox

**Git repository url:** https://github.com/fancyapps/fancybox

**npm package name or url** (if there is one): https://www.npmjs.com/package/fancybox (not official)

**License (List them all if it's multiple):**
fancyBox is licensed under the GPLv3 license for all open source applications. 
A commercial license is required for all commercial applications (including sites, themes and apps you plan to sell).

**Official homepage:** http://fancyapps.com/fancybox/3/

**Wanna say something? Leave message here:**
Please update your library to the latest version 3.
It is currently being hosted by cdnjs but you have the old version 2.1.6.
https://cdnjs.com/libraries/fancybox

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by fancyapps** [comment] 2017-03-06 07:51
Hi! I just wanted to say that fancybox does not have official npm package. The one mentioned above is a modified fork by someone else.

**Comment by PeterDaveHello** [comment] 2017-03-06 07:52
@fancyapps thanks for that info!

**Comment by fancyapps** [comment] 2017-03-06 22:07
If you need a git tag for versioning, I have tagged "v3.0.39" release - https://github.com/fancyapps/fancybox/releases/tag/3.0.39

btw, this is duplicate of #10758

**Comment by PeterDaveHello** [comment] 2017-03-08 10:01
Move to #6191

**Closed by PeterDaveHello** 2017-03-08 10:01 UTC
Labels: High Priority, Library - Request to Add/Update
