### ISSUE TITLE
[Request] Add Loadie.js 

### ISSUE THREAD

**Issue by ipankajthakur** [cdnjs/cdnjs#8540] opened 2016-07-18 10:15 UTC
**Library name:** Loadie.js
**Git repository url:_https://github.com/9elements/loadie.js_
**npm package url(optional):** 
**License(s):**
**Official homepage:_http://9elements.github.io/loadie.js/_
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment] 2017-11-30 11:34
@PeterDaveHello @maruilian11 It seems that this lobrary has only 1 version [v1.0](https://github.com/9elements/loadie.js#options), maybe we could add it manually? What do you think?

**Comment by PeterDaveHello** [comment] 2017-12-02 16:47
The problem is that we can't identify/locate the v1.0, so we can't manually add it.

**Comment by sashberd** [comment] 2017-12-03 09:15
@PeterDaveHello Why? Here, in the link above, it is clearly said that: "At this moment Loadie.js (**v1.0**) doesn't support extensive options... ". So we could add it from master as v1.0

**Comment by PeterDaveHello** [comment] 2017-12-03 09:17
@sashberd That's not acceptable at all, v1.0 should be a static reference, a branch is NOT.

**Comment by sashberd** [comment] 2017-12-03 09:19
@PeterDaveHello Well, I suggest to close this one

**Closed** 2020-02-20 19:08 UTC
Labels: :arrows_counterclockwise: Wait for response, :wastebasket: Suggest to close, in progress, 🏷 Library Request
