### ISSUE TITLE
File missing in toastr repository

### ISSUE THREAD

**Issue by TimFerrell** [cdnjs/cdnjs#8779] opened 2016-08-19 13:50 UTC
```
The minified JS is no logner present from the following path:
https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js

However the unminified is still present:
https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.js
```
- @ninio

Please see: https://github.com/CodeSeven/toastr/issues/453

This issue started in the past few days.

**Comment by PeterDaveHello** [comment] 2016-08-19 15:28
@TimFerrell Thanks.

**Comment by dschuermans** [comment] 2016-08-22 07:15
I'm pretty sure this a duplicate of https://github.com/cdnjs/cdnjs/issues/8565

Maybe it's best if the toastrjs page updates its readme, notifying users of the breaking change in the cdn url.
PS: The cached version is no longer working for me either anymore ;) So my guess is more and more people will show complaining about this issue.

**Comment by PeterDaveHello** [comment] 2016-08-23 13:50
@dschuermans you are right, I'm now closing this PR.

**Closed by PeterDaveHello** 2016-08-23 13:50 UTC
