### ISSUE TITLE
Search for "backbone" doesn't yield backbone.js

### ISSUE THREAD

**Issue by jmm** [cdnjs/cdnjs#4368] opened 2015-02-17 16:15 UTC
FYI, if I search the site for `backbone` I get a bunch of libs with `backbone` in the name, but not backbone itself. I have to search for `backbone.js` or `backbone.j` to get backbone.

**Comment by PeterDaveHello** [comment] 2015-02-17 17:04
Oops, I need to call out for help ... I am not sure if is algolia's issue or not.

Dear @thomasdavis & @redox, would you please take a look at this issue? thanks.

**Comment by redox** [comment] 2015-02-17 21:53
I'm on it, related to Algolia's ranking formula conflicting with the exact matches we have in the "keyword" attribute. I'll check what I can do.

**Comment by redox** [comment] 2015-02-18 01:27
Should be fixed after reindexing.

**Comment by PeterDaveHello** [comment] 2015-02-18 03:44
@jmm and you help us confirm this issue? thanks!

**Comment by jmm** [comment] 2015-02-18 14:30
@PeterDaveHello It's unchanged for me (and browser caching isn't an issue). The reindexing that @redox referred to would have already happened by now?

**Comment by redox** [comment] 2015-02-18 14:38
From what I see, the https://github.com/cdnjs/new-website/blob/master/public/packages.json file is still mentioning the previous backbone.js repository -> what is the best way to refresh that file? I can then start the reindexing manually.

**Comment by PeterDaveHello** [comment] 2015-02-18 17:17
Okay, I'll try to update it, because @thomasdavis changed something without push it out, so that I can not directly update as him, not sure if my update will work, let me try now.

**Comment by PeterDaveHello** [comment] 2015-02-18 17:25
@redox I think I updated it, but I have no api key to reindex it, maybe you can give me that in private so that we can fix this issue easier next time, I can't find Thomas sometimes, so that we'll need to wait for him, or let me update the package and let you reindex, will be a little bit complex.

**Comment by redox** [comment] 2015-02-18 18:49
I've run the reindexing + added a new PR to improve the overall ranking. I'm now sending you the Algolia  API key + GitHub OAuth token to run the reindexing.

**Comment by PeterDaveHello** [comment] 2015-02-19 07:44
Thanks @redox !

@jmm would you please check if this okay now for you? I can see backbone.js via keyword backbone now, just at the bottom of that page, thanks!

**Comment by redox** [comment] 2015-02-19 07:50
I've just started the indexing. Now it's OK -> I assume a reindexing has been done before my other PR (about "exact" ranking criteria) has been merged. The expected behavior is to have the backbone.js library as the 1st result.

**Comment by thomasdavis** [comment] 2015-02-19 07:51
Great work @redox and @PeterDaveHello you guys killed it =D

@redox the script is set to run every 30 minutes at the moment so should be fine.

**Comment by PeterDaveHello** [comment] 2015-02-19 07:53
Hey @thomasdavis, finally you are now here, can we talk on gitter now? thanks!

**Comment by redox** [comment] 2015-02-19 07:53
Hehe :+1: @thomasdavis alright for the script, good to know :)

**Comment by jmm** [comment] 2015-02-19 14:37
@PeterDaveHello Yes, it now works as I'd expect: "backbone" produces backbone.js as the 1st result. In fact, by the time I get to "b", it's the # 2 result, and by the time I get to "ba" it's # 1.

**Comment by PeterDaveHello** [comment] 2015-02-20 03:49
Okay, then I'll close this issue, thanks.

**Closed by PeterDaveHello** 2015-02-20 03:49 UTC
