### ISSUE TITLE
[Request] Update React to 15.4.1

### ISSUE THREAD

**Issue by GiedriusGrabauskas** [cdnjs/cdnjs#9782] opened 2016-11-29 13:00 UTC
**Library name:** react
**Git repository url:** https://github.com/facebook/react
**npm package url(optional):** https://www.npmjs.com/package/react
**Official homepage:** https://facebook.github.io/react/

Issue about `react@15.4.0` problem: https://github.com/facebook/react/issues/8301

**Comment by pvnr0082t** [comment] 2016-12-02 16:56
@PeterDaveHello https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/react/package.json#L19 fetch file from https://github.com/reactjs/react-bower not https://github.com/facebook/react. 
Should we change the target to https://github.com/facebook/react or wait for v15.4.1 released on https://github.com/reactjs/react-bower?

**Comment by PeterDaveHello** [comment] 2016-12-02 17:07
hmmmm ... maybe ping the react-bower repo? Since there won't be dist files in main repo, or did they just change it?

**Comment by pvnr0082t** [comment] 2016-12-02 17:28
@PeterDaveHello There is dist folder on NPM. https://unpkg.com/react@15.4.1/dist/. Can we use this?

**Comment by PeterDaveHello** [comment] 2016-12-02 18:35
If you confirmed that that's what we need, sure!

**Comment by pvnr0082t** [comment] 2016-12-04 08:03
Updated to 15.4.1. https://cdnjs.com/libraries/react
I'm going to close this issue. Thanks for your contribution.@GiedriusGrabauskas

**Closed by pvnr0082t** 2016-12-04 08:03 UTC
Labels: High Priority, Library - Request to Add/Update

**Comment by PeterDaveHello** [comment] 2016-12-04 09:28
@pvnr0082t could also provide the commit as reference: https://github.com/cdnjs/cdnjs/commit/ebedc7fdfa8e8c292188d64cb756266a8d15590e#diff-6b1a023d56892850ad3b9cc5717d29b4
