### ISSUE TITLE
cdnjs website & API erroring for some libraries

### ISSUE THREAD

**Issue by souvik362** [cdnjs/cdnjs#13986] opened 2020-06-12 04:16 UTC
When I click on a package the website is showing:

```
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail
```

I originally encountered this at https://cdnjs.com/libraries/nightly.js

**Comment by VenatusSimpleX** [comment] 2020-06-12 07:24
Issue is still ongoing, unable to access the main website:
![8bfb4fbb_ss_2020-06-12_15-22-47](https://user-images.githubusercontent.com/31540342/84476379-9e6f1600-acc0-11ea-90a4-b1d7237b4cfd.png)

However, status.cdnjs.com shows that all systems are green:
![c404df02_ss_2020-06-12_15-24-06](https://user-images.githubusercontent.com/31540342/84476465-c52d4c80-acc0-11ea-8501-b21abb01de86.png)

**Comment by MattIPv4** [comment] 2020-06-12 08:28
@souvik362 Thanks for the report!

@VenatusSimpleX could you share which pages you're able to reproduce this error on?

I'm just publoshing a status incident now (the page is manually run, not automated, so that incidents appear once we're aware and investigating).

**Comment by MattIPv4** [comment] 2020-06-12 08:32
I have published an incident for this: https://status.cdnjs.com/incidents/wqcpnncl4c7n

**Comment by MattIPv4** [comment] 2020-06-12 08:32
I can reliably reproduce the error on both the website and API with `geojson`: https://cdnjs.com/libraries/geojson & https://api.cdnjs.com/libraries/geojson

cc @xtuc

**Comment by MattIPv4** [comment] 2020-06-12 08:43
Using my local copy of the API server, this seems to be stemming from the JSON data file for all cdnjs libraries being incomplete.

```
cat data/packages.min.json | jq .
parse error: Unfinished string at EOF at line 1, column 112025600
```

**Comment by MattIPv4** [comment] 2020-06-12 08:50
Looking at the source for the JSON data file, it is cut off at the same point, so the issue seems to lie with the generation of this file rather than with the website or API directly: `https://storage.googleapis.com/cdnjs-assets/package.min.js`

**Comment by MattIPv4** [comment] 2020-06-12 09:05
Mitigation for this in the future:

When the API updates itself every 10 minutes, it should not immediately overwrite its current copy of the JSON package data, but copy it to a new file and use `jq` to validate the file before replacing the current JSON and loading it into memory.

The current logic simply replaces the existing JSON file and loads it into memory -- this is fine for auto-updating as it'll update the JSON file and then fail to parse it if it is invalid, leaving the old data in memory. However, if for any reason the API gets restarted then it will only have the invalid JSON to attempt to load in and as such fail.

**Comment by MattIPv4** [comment] 2020-06-12 11:16
Both the API & website should be back up and running. We've added some mitigation logic to the API as noted above to hopefully prevent this happening again, and I'll continue working on the new website stack so we can replace the existing one.

**Comment by VenatusSimpleX** [comment] 2020-06-12 12:17
Ah, thank you for such a quick response and sorry for failing to reply to you during that time.

Can confirm website now works. Thanks for your hard work!
![7fc13334_ss_2020-06-12_20-17-22](https://user-images.githubusercontent.com/31540342/84501815-be66ff80-ace9-11ea-81ba-9f25f97d5f65.png)

I guess for the record- It error-ed out right at the homepage.

**Comment by MattIPv4** [comment] 2020-06-12 12:19
Just marked the incident as resolved, will now close this issue.

**Closed by MattIPv4** 2020-06-12 12:19 UTC
Labels: :rotating_light: High Priority

**Comment by viktorcos** [comment] 2020-06-22 07:28
I am still seeing this issue for the API. https://cdnjs.com/libraries/geojson works while https://api.cdnjs.com/libraries/geojson returns 502.

**Comment by MattIPv4** [comment] 2020-06-22 08:08
@viktorcos thanks for the report, looking into it :)

**Comment by MattIPv4** [comment] 2020-06-22 08:57
Should be resolved :)

**Comment by viktorcos** [comment] 2020-06-22 09:16
Yes, it is working now, thank you.
