### ISSUE TITLE
[Request] New repo with just the library definitions

### ISSUE THREAD

**Issue by stuartpb** [cdnjs/cdnjs#4718] opened 2015-06-08 19:33 UTC
It's ridiculous that I should have to clone and checkout **a gigabyte of content** just to add a 50-line package.json. I've seen https://github.com/cdnjs/new-cdnjs - that's not a solution. The *definitions* of the CDN should be versioned and stored *entirely* separately from their evaluations (the content).

**Comment by IonicaBizau** [comment] 2015-06-08 19:39
Currently the solution is to use [`cdnjs-importer`](https://github.com/IonicaBizau/cdnjs-importer) - a tool I wrote to make this process easier. However, you have to clone the cdnjs repo on your machine.

This is a duplicate of #4461.

**Closed** 2015-06-08 19:40 UTC
Labels: Duplicate

**Comment by thomasdavis** [comment] 2015-06-08 19:41
@stuartpb you should also be able to use the --depth option -> http://git-scm.com/docs/git-clone

**Comment by stuartpb** [comment] 2015-06-08 19:43
@thomasdavis The checkout itself is still massive, and there's no way to specify clone depth when creating a workspace on https://c9.io.

**Comment by stuartpb** [comment] 2015-06-08 19:49
Even `git clone --depth 1 git@github.com:cdnjs/cdnjs.git` pulls 608.99 MB, and that's *before* any files are checked out.

**Comment by PeterDaveHello** [comment] 2015-06-08 20:31
The repo size is not the root cause of performance, try sparse checkout:
https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md
