### ISSUE TITLE
Future architecture of cdnjs

### ISSUE THREAD

**Issue by gionkunz** [cdnjs/cdnjs#3713] opened 2014-08-10 20:06 UTC
Hi guys,

First thanks so much for your effort here. It's very cool to have an open source CDN in place!

I was wondering why you keep all the libraries in the repository? Wouldn't it make more sense to exclude the libraries folder from GIT and have a separate file (i.e. libraries.json) with only the meta data? This could be stored in one single JSON like so:

```json
  "Lo-Dash": {
    "repository": {
      "type": "git",
      "url": "https://github.com/lodash/lodash.git"
    },
    "basePath": "dist",
    "files": [
      "*.js"
    ]
  },
  "jQuery": {
    "repository": {
      "type": "npm",
      "url": "https://registry.npmjs.org/jquery"
    },
    "basePath": "dist",
    "files": [
      "jquery.js",
      "jquery.min.js",
      "jquery.min.map"
    ]
  }
```

An adapter that is abstracting the repository away which allows to pre-fetch version information (tags in git and JSON reply from NPM) that is relying on semver would be nice and fast. There is no need for adding a package.json in my opinion. The service should be able to read the package.json, bower.json or composer.json on fetch and read the necessary information from there. Pull requests should only be done with the libraries.json. The directory that serves the users with the libraries on the server should be decoupled from the repository and automatically be built / updated from the automatic updater.

I'd be more than happy to contribute on some parts if you're planning to switch the architecture into this direction. Currently I find it quite painful to fetch a 300mb repository in order to add my own library.

Cheers
Gion

**Comment by drewfreyling** [comment] 2015-01-12 23:12
This is sort of a duplicate of #3941

**Comment by thomasdavis** [comment] 2015-01-13 09:25
Thanks for assigning!

We are working on this, we just have to make sure the origin servers are a perfect mapping of what is there already.

**Comment by PeterDaveHello** [comment] 2015-03-23 15:59
Reference, may help, may not.
https://git-annex.branchable.com/

**Comment by PeterDaveHello** [comment] 2015-04-27 22:59
Lets' just discuss in #3941, thanks!

**Closed by PeterDaveHello** 2015-04-27 22:59 UTC
