### ISSUE TITLE
[Request] Add tempusdominus

### ISSUE THREAD

**Issue by benjdl** [cdnjs/cdnjs#11778] opened 2017-09-04 21:26 UTC
**Library name:** tempusdominus
**Library desctiption:** rewrite of bootstrap-datetimepicker for BS4
**Git repository url:** https://github.com/tempusdominus/bootstrap-4
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** https://tempusdominus.github.io/bootstrap-4/
**Wanna say something? Leave message here:**

**Comment by extend1994** [comment] 2017-09-05 11:42
Hi @benjdl 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :smile:
We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by NullVoxPopuli** [comment] 2017-10-25 16:52
not having cdn access is a blocker to popularity, imo. I would have used this library if it were on the CDN. :_\

**Comment by Eonasdan** [comment] 2017-10-25 21:34
duplicate of #11453

**Comment by sufuf3** [comment] 2017-10-27 01:38
@Eonasdan Thanks.
close this issue because duplicated with #11453 
Let's move to #11453 
cc @PeterDaveHello

**Closed by sufuf3** 2017-10-27 01:38 UTC
Labels: Library - Request to Add/Update, Library - wait for notable popularity
