### ISSUE TITLE
flag-icon-css not automatically updated

### ISSUE THREAD

**Issue by holtkamp** [cdnjs/cdnjs#13270] opened 2019-02-26 17:09 UTC
Also see https://github.com/lipis/flag-icon-css/issues/535

---
[flag-icon-css](https://cdnjs.com/libraries/flag-icon-css) is configured to automatically update with https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/flag-icon-css/package.json

Version [`3.3.0`](https://github.com/flag-icon-css/moment/releases) has been tagged a day ago, but seems not detected by the CDNJS bot, resulting in a 404 page for:

https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/css/flag-icon.min.css

The last version `3.2.1` seem to have been _authored_ by the @PeterBot but _committed_ by @PeterDaveHello, so the automation seems not 100%...

https://github.com/cdnjs/cdnjs/search?q=flag-icon-css&type=Commits

**Comment by PeterDaveHello** [comment] 2019-02-26 18:13
@holtkamp the only reason I'm the committer would be caused by rebasing branch, that's not a common case, usually triggered by bot hanging events with inconsistent commit status,  for example:
The bot committed 10 commits but hangs on the server for a while, during that period, some commits are merged on GitHub, that when I step in, I'll rebase the local branch, otherwise, it's 100% automatically.

**Comment by PeterDaveHello** [comment] 2019-02-26 18:16
@holtkamp v3.3.0 was not added not becaused it's not detected, on the other hand, it's detected with different file/driectory structure. which needs a manual step in to confirm everything is good, we host more than 3k libraries, with different situations, sometimes the changes are not expected, the bot only commit a version if the structure wasn't change.

**Comment by PeterDaveHello** [comment] 2019-02-26 18:16
@holtkamp in this case, two new files detected:
- ./flags/1x1/xk.svg
- ./flags/4x3/xk.svg

**Closed** 2019-02-26 19:33 UTC

**Comment by holtkamp** [comment] 2019-02-26 22:06
ok, thanks for the swift reaction. 

https://github.com/cdnjs/cdnjs/issues/13270#event-2165926612

Understood, please do not get me wrong: I did not want to offend anybody and got big respect for CDNJS...

https://github.com/cdnjs/cdnjs/issues/13270#issuecomment-467551652

mmm, yeah, every time a new flag is added, that would result in new files... Maybe we can make the bot aware of this possibility?

**Comment by PeterDaveHello** [comment] 2019-03-02 07:26
No worries at all.
I think it's really not possible to make a bot handle it, even a human takes time to confirm the changes, unless we have AI or ML bot, I don't know a way to do so, especially we don't have the resource to do so.
