### ISSUE TITLE
[Request] Add _MyBB-Cssjs-files_ 

### ISSUE THREAD

**Issue by vikili** [cdnjs/cdnjs#5027] opened 2015-07-19 09:01 UTC
Hi

Please add a lib of mybb forum software

**Comment by Piicksarn** [comment] 2015-08-09 12:50
@vikili would you please provide the `git repository url` or `npm package url`, so that we could add library efficiently.

Thank you!

**Comment by vikili** [comment] 2015-08-09 13:40
Hi,

this Is git repository

https://github.com/mybb/mybb

please add this to cdnjs

**Comment by Piicksarn** [comment] 2015-08-09 13:50
@vikili Thanks!

**Comment by maruilian11** [comment] 2016-11-22 04:22
@PeterDaveHello this lib seems a php lib, do we need to host it?

**Comment by PeterDaveHello** [comment] 2016-11-22 05:11
@maruilian11 the request is for css and js file, isn,'t it?

**Comment by PeterDaveHello** [comment] 2016-11-22 07:39
@vikili as this is not a frontend library, this is a php built forum system, we may not add this unless mybb guys would like to do it and support for CDN, without the official support from mybb, the cdn hosting may be meaningless, thanks.

**Comment by euantorano** [comment] 2016-11-22 11:58
Regarding the CSS and JS in MyBB, the CSS for the base theme is stored in a cache folder, but 99% of sites don't use the default theme.

The JS often isn't changed, but we have built in support for "pull" type CDNs that can be configured in the software for users wishing to us it - the problem is that this is an all or nothing solution so all images, JS and CSS would have to be on the CDN.

**Comment by PeterDaveHello** [comment] 2016-11-22 12:02
@euantorano so would you like to help us hosting this and make sure MyBB support it? What's the files need to be hosted?

**Comment by euantorano** [comment] 2016-11-22 12:31
@PeterDaveHello At the minute I'm not sure it's worth the effort it would require to be honest.

**Comment by PeterDaveHello** [comment] 2016-11-22 12:36
I also have concern about this, that's why I'm asking for help from MyBB team :)
Maybe we could just close this at the meantime, once MyBB team would like to do this together, we'll reopen and try to host it again, Thanks.

**Closed by PeterDaveHello** 2016-11-22 12:36 UTC
Labels: Help wanted, Library - Request to Add/Update
