### ISSUE TITLE
[Request] materialdesignicons v1.1.70

### ISSUE THREAD

**Issue by ugate** [cdnjs/cdnjs#5341] opened 2015-08-12 15:28 UTC
https://materialdesignicons.com/
https://github.com/templarian/MaterialDesign/
https://materialdesignicons.com/getting-started

  /materialdesignicons-webfont.eot
  /materialdesignicons-webfont.svg
  /materialdesignicons-webfont.ttf
  /materialdesignicons-webfont.woff
  /materialdesignicons-webfont.woff2
  /materialdesignicons.min.css

**Comment by Piicksarn** [comment] 2015-08-12 15:33
[Consider adding tags for the repo. #602](https://github.com/Templarian/MaterialDesign/issues/602)

**Comment by Piicksarn** [comment] 2015-08-12 15:41
@ugate, this PR duplicate of #4993
We need the author of library adds the tags, so that we are able to confirm the version number.

**Closed** 2015-08-12 15:46 UTC
